function saveOutputsTERRA(casePath, caseName, result, source, units, labels, levels, species, prob_setup, overwrite)
% Save structures generated by ReadOutput.m to a .mat file in the case
% directory. Prompt user if this will involve an overwrite of a previous
% .mat file with the same name in the case directory.

  % Get the current path for later return
  runPath = pwd;

  % Change into case directory and construct file to save
  cd(casePath)
  saveName = sprintf('%s.mat',strrep(caseName,' ','_'));

  % Save and file and interact with the user as needed
  fprintf('\n');
  if isfile(saveName) && ~(overwrite)
    answer = questdlg(sprintf('Saved output %s already exists. Replace?',saveName), ...
      'Replace File?', ...
      'Yes','No','No');
    % Overwrite if the user says to
    if strcmp(answer,'Yes')
      save(saveName,'result','source','units','labels','levels','species','prob_setup');
      disp('File successfully saved.')
    % Don't overwrite the file if the user says so
    else
      disp('File not saved.')
    end
  else
    save(saveName,'result','source','units','labels','levels','species','prob_setup');
  end

  % Return to the run path
  cd(runPath)
end
